source 'https://github.com/CocoaPods/Specs.git'


platform :ios, '7.0'

target 'MyImage' do
    pod 'AFNetworking' , '2.5.4'
    pod 'SVPullToRefresh' , '0.4.1'
    pod 'Masonry' , '0.6.2'
    pod 'GPUImage' , '0.1.7'
    pod 'TMCache' , '2.1.0'
end


target 'MyImageTests' do
    
end

